# hospital
DISEASE_STATUSES = {
    0: "Тяжело болен", 
    1: "Болен", 
    2: "Слегка болен", 
    3: "Готов к выписке"
}
DISEASE_STATUSES_REVERSED = {value: key for key, value in DISEASE_STATUSES.items()}

DEFAULT_DISEASE_ID = 1


DEFAULT_USERS_COUNT = 200

# commands
STOP_CMD_RU = "стоп"
STOP_CMD_EN = "stop"
STOP_CMDS = (STOP_CMD_RU, STOP_CMD_EN)

STAT_CMD_RU = "рассчитать статистику"
STAT_CMD_EN = "calculate statistics"
STAT_CMDS = (STAT_CMD_RU, STAT_CMD_EN)

DECREASE_PATIENT_STAT_CMD_RU = "понизить статус пациента"
DECREASE_PATIENT_STAT_CMD_EN = "status down"
DECREASE_PATIENT_STAT_CMDS = (DECREASE_PATIENT_STAT_CMD_RU, DECREASE_PATIENT_STAT_CMD_EN)
INCREASE_PATIENT_STAT_CMD_RU = "повысить статус пациента"
INCREASE_PATIENT_STAT_CMD_EN = "status up"
INCREASE_PATIENT_STAT_CMDS = (INCREASE_PATIENT_STAT_CMD_RU, INCREASE_PATIENT_STAT_CMD_EN)
GET_PATIENT_STAT_CMD_RU = "узнать статус пациента"
GET_PATIENT_STAT_CMD_EN = "get id"
GET_PATIENT_STAT_CMDS = (GET_PATIENT_STAT_CMD_RU, GET_PATIENT_STAT_CMD_EN)

PATIENT_CMDS = DECREASE_PATIENT_STAT_CMDS + INCREASE_PATIENT_STAT_CMDS + GET_PATIENT_STAT_CMDS

INPUT_COMMAND_TEXT = "Введите команду: "
INPUT_PATIENT_ID_COMMAND_TEXT = "Введите ID пациента: "

PATIENT_ID_INPUT_TEXT = "Ошибка ввода. ID пациента должно быть числом (целым, положительным)"
