# commands
STOP_CMD_RU = "стоп"
STOP_CMD_EN = "stop"
STOP_CMDS = (STOP_CMD_RU, STOP_CMD_EN)

STAT_CMD_RU = "рассчитать статистику"
STAT_CMD_EN = "calculate statistics"
STAT_CMDS = (STAT_CMD_RU, STAT_CMD_EN)

DECREASE_PATIENT_STAT_CMD_RU = "понизить статус пациента"
DECREASE_PATIENT_STAT_CMD_EN = "status down"
DECREASE_PATIENT_STAT_CMDS = (DECREASE_PATIENT_STAT_CMD_RU, DECREASE_PATIENT_STAT_CMD_EN)
INCREASE_PATIENT_STAT_CMD_RU = "повысить статус пациента"
INCREASE_PATIENT_STAT_CMD_EN = "status up"
INCREASE_PATIENT_STAT_CMDS = (INCREASE_PATIENT_STAT_CMD_RU, INCREASE_PATIENT_STAT_CMD_EN)
GET_PATIENT_STAT_CMD_RU = "узнать статус пациента"
GET_PATIENT_STAT_CMD_EN = "get id"
GET_PATIENT_STAT_CMDS = (GET_PATIENT_STAT_CMD_RU, GET_PATIENT_STAT_CMD_EN)

PATIENT_CMDS = DECREASE_PATIENT_STAT_CMDS + INCREASE_PATIENT_STAT_CMDS + GET_PATIENT_STAT_CMDS
